parameters:
#    five_tsdh_api.example.class: Five\TSDHApiBundle\Example

services:
#    five_tsdh_api.example:
#        class: %five_tsdh_api.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]