imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @FiveAdminBundle/Resources/config/admin/_sidebar.yml }
    - { resource: '@FiveAdminBundle/Resources/config/admin/branch.yml' }
    - { resource: '@FiveAdminBundle/Resources/config/admin/gallery.yml' }
    - { resource: '@FiveAdminBundle/Resources/config/admin/mailer.yml' }
    - { resource: '@FiveAdminBundle/Resources/config/admin/user.yml' }
    - { resource: '@FiveAdminBundle/Resources/config/admin/blog.yml' }
    #- { resource: '@FiveAdminBundle/Resources/config/admin/news.yml' }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug: true
    strict_variables: true
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    form:
        resources:
            - BraincraftedBootstrapBundle:Form:bootstrap.html.twig
            #- SonataAdminBundle:Form:silex_form_div_layout.html.twig
            #- SonataFormatterBundle:Form:formatter.html.twig
            #- 'FiveAdminBundle:Form:fields.html.twig'
            #- "FiveTranslationFormBundle::form.html.twig"
    globals:
        interface_sidebar: "%five_admin.interface.sidebar%"
        locales: "%managed_locales%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:         [ 'FiveCuisinesVerdunBundle', 'FiveAdminBundle']
    #java: /usr/bin/java
    node:                 /usr/local/bin/node
    filters:
        # cssrewrite:
        #     apply_to: "\.css$"
        sass:
            bin: %assetic.sass.bin%
            style: expanded
            #apply_to: "\.(scss|sass)$"
        compass:
            bin: %assetic.compass.bin%
        uglifyjs2:
            bin: "/usr/local/bin/uglifyjs"
        uglifycss:
            bin: "/usr/local/bin/uglifycss"
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

braincrafted_bootstrap:
    less_filter: none
    auto_configure:
        assetic:       false
        twig:          true
        knp_menu:      false
        knp_paginator: false

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        dql:
            string_functions:
                replace: Doctrine\ORM\Query\AST\Functions\replaceFunction

prezent_doctrine_translatable:
    fallback_locale: "%locale%"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    encryption: ssl
    spool:     { type: memory }

mobile_detect:
    redirect:
        mobile:
            is_enabled: ~
        tablet:
            is_enabled: ~
    switch_device_view: ~


jms_aop:
    cache_dir: %kernel.cache_dir%/jms_aop

a2lix_translation_form:
    locales: "%managed_locales%"
    required_locales: ["%locale%"]       # [1]
    #default_required: true      # [2]
    manager_registry: doctrine      # [3]
    templating: "A2lixTranslationFormBundle::default.html.twig"      # [4]

nelmio_api_doc: ~

jms_serializer:
    handlers:
        datetime:
            default_format: "Y-m-d H:i:s" # ISO8601
            default_timezone: "UTC" # defaults to whatever timezone set in php.ini or via date_default_timezone_set
    property_naming:
        separator:  _
        lower_case: true
    metadata:
        cache: file
        debug: "%kernel.debug%"
        file_cache:
            dir: "%kernel.cache_dir%/serializer"
        auto_detection: true
    visitors:
        json:
            options: 0 # json_encode options bitmask

fos_rest:
    routing_loader:
        default_format: json
    view:
        #view_response_listener: 'force'
        formats:
            json: true
        templating_formats:
            html: true
    disable_csrf_role:    null
    param_fetcher_listener:  true
    cache_dir:            '%kernel.cache_dir%/fos_rest'
    allowed_methods_listener:  false
    routing_loader:
        default_format:       json
        include_format:       false
mobile_detect:
    redirect:
        mobile:
            is_enabled: true            # default false
            action: no_redirect         # redirect, no_redirect, redirect_without_path
        tablet:
            is_enabled: true            # default false
            action: no_redirect         # redirect, no_redirect, redirect_without_path
        detect_tablet_as_mobile: true   # default false
    switch_device_view:
        save_referer_path: false        # default true
                                        # true  redirectUrl = http://site.com/current/path?currentQuery=string
                                        # false redirectUrl = http://site.com
    service:
        mobile_detector: mobile_detect.mobile_detector.default
    device_view_class: SunCat\MobileDetectBundle\Helper\DeviceView
    request_listener_class: SunCat\MobileDetectBundle\EventListener\RequestListener
    extension_class: SunCat\MobileDetectBundle\Twig\Extension\MobileDetectExtension

services:
    twig.text_extension:
        class: Twig_Extensions_Extension_Text
        tags:
            - name: twig.extension


    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ @annotation_reader ] ]

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }        
            
fm_elfinder:
    instances:
        default:
            locale: %locale% # defaults to current request locale
            editor: ckeditor # other options are tinymce, tinymce4, form, custom and simple
            fullscreen: true # defaults true, applies to simple and ckeditor editors
            theme: smoothness # jquery theme
            include_assets: true # disable if you want to handle loading of the javascript and css assets yourself
            connector:
                debug: false # defaults to false
                roots:       # at least one root must be defined
                    uploads:
                        show_hidden: false # defaults to false
                        driver: LocalFileSystem
                        path: uploads/blog
                        upload_allow: ['image/png', 'image/jpg', 'image/jpeg']
                        upload_deny: ['all']
                        upload_max_size: 2M

ivory_ck_editor:
    default_config: default
    configs:
        default:
            filebrowserBrowseRoute: elfinder
            filebrowserBrowseRouteParameters: []
            extraPlugins : templates