parameters:
    database_driver:   pdo_mysql
    database_host:     localhost
    database_port:     ~
    database_name:     pfverdun_prod
    database_user:     pfverdun
    database_password: "*tp$[U_WPyn("

    mailer_transport:  sendmail
    mailer_host:       ~
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            c39178826b4adb8836fca7a5c7b3869b9f11230b