#BloggerBlogBundle_blog_index:
#    pattern:  /blog/
#    defaults: { _controller: BloggerBlogBundle:Page:index }
#    requirements:
#        _method:  GET

#BloggerBlogBundle_page_latest:
#    pattern:  /blog/
#    defaults: { _controller: BloggerBlogBundle:Page:latest }



#BloggerBlogBundle_blog_show:
#    pattern:  /blog/{id}
#    defaults: { _controller: BloggerBlogBundle:Blog:show }
#    requirements:
#        _method:  GET
#        id: \d+
        

    
#Blog
blog_en:
    pattern:  /{_locale}/blog/{blog_page}/{blog_tag}
    defaults: { _controller: "FiveCuisinesVerdunBundle:User:blog", blog_page: 1 ,  blog_tag: ""  }
    requirements:
        _locale: en
        blog_page: \d+


blog_fr:
    pattern:  /{_locale}/blog/{blog_page}/{blog_tag}
    defaults: { _controller: "FiveCuisinesVerdunBundle:User:blog", blog_page: 1 ,  blog_tag: ""  }
    requirements:
        _locale: fr    
        blog_page: \d+


#blog_tag_en:
#    pattern:  /{_locale}/blog/tag/{blog_tag}/{blog_page}
#    defaults: { _controller: "FiveCuisinesVerdunBundle:User:blogTag", blog_tag: "" , blog_page: 1 }
#    requirements:
#        _locale: en
#
#
#blog_tag_fr:
#    pattern:  /{_locale}/blog/tag/{blog_tag}/{blog_page}
#    defaults: { _controller: "FiveCuisinesVerdunBundle:User:blogTag", blog_tag: "" , blog_page: 1 }
#    requirements:
#        _locale: fr    
    
#Blog
#blog_article_en:
#    pattern:  /{_locale}/blog_article/{blog_id}/{home}
#    defaults: { _controller: "FiveCuisinesVerdunBundle:User:blogAricle" , blog_id : 0 , home : 0  }
#    requirements:
#        _locale: en
#        blog_id: \d+


#blog_article_fr:
#    pattern:  /{_locale}/blog_article/{blog_id}/{home}
#    defaults: { _controller: "FiveCuisinesVerdunBundle:User:blogAricle", blog_id : 0 , home : 0 }
#    requirements:
#        _locale: fr
#        blog_id: \d+
  
#Blog
blog_article_en:
    pattern:  /{_locale}/blog/{permalink}
    defaults: { _controller: "BloggerBlogBundle:Blog:show" , permalink : ''   }
    requirements:
        _locale: en
        blog_id: \d+


blog_article_fr:
    pattern:  /{_locale}/blog/{permalink}
    defaults: { _controller: "BloggerBlogBundle:Blog:show", permalink : ''  }
    requirements:
        _locale: fr
        blog_id: \d+
        
blog_article_home_en:
    pattern:  /{_locale}/blog-article-home/{permalink}
    defaults: { _controller: "FiveCuisinesVerdunBundle:User:blogAricleHome" , permalink : ''   }
    requirements:
        _locale: en

blog_article_home_fr:
    pattern:  /{_locale}/blog-article-home/{permalink}
    defaults: { _controller: "FiveCuisinesVerdunBundle:User:blogAricleHome", permalink : ''  }
    requirements:
        _locale: fr
        
        
        
blog_like_click:
    pattern:  /blog/like-click
    defaults: { _controller: "BloggerBlogBundle:Blog:likeClick" }


        