five_admin_home:
    path:     /
    defaults: { _controller: FiveAdminBundle:Default:index }


five_admin_user:
    resource: "@FiveAdminBundle/Resources/config/routing/user.yml"
    prefix:   /user

five_admin_upload_pictures:
    path:     /upload/pictures
    defaults: { _controller: FiveAdminBundle:Crud:uploadPictures }
    

# five_admin_translation:
#     resource: "@FiveAdminBundle/Resources/config/routing/translation.yml"
#     prefix:   /translation
#     options: { i18n: false }
api_five_edit_property:
    pattern: /api/five/edit/{bundle}/{entity}/{id}/{property}
    defaults: { _controller: FiveAdminBundle:FiveAdminEdit:propertyUpdate }

five_admin_webtest:
    resource: "@FiveAdminBundle/Resources/config/routing/webtest.yml"
    prefix:   /webtest

five_admin_info:
    path:     /info
    defaults: { _controller: FiveAdminBundle:Default:info }

five_admin_branch_list:
    path:     /branch
    defaults: { _controller: FiveAdminBundle:Crud:list, options: 'five_admin.crud.branch_list' }

five_admin_branch_edit:
    path:     /branch/{id}/edit
    defaults: { _controller: FiveAdminBundle:Crud:edit, options: 'five_admin.crud.branch_edit' }

five_admin_branch_delete:
    path:     /branch{id}/delete
    defaults: { _controller: FiveAdminBundle:Crud:delete, options: 'five_admin.crud.branch_delete', entityName: 'FiveCuisinesVerdunBundle:Branch' }

five_admin_branch_create:
    path:     /branch/create
    defaults: { _controller: FiveAdminBundle:Crud:create, options: 'five_admin.crud.branch_create' }



five_admin_program_list:
    path:     /program
    defaults: { _controller: FiveAdminBundle:Crud:list, options: 'five_admin.crud.program_list' }

five_admin_program_edit:
    path:     /program/{id}/edit
    defaults: { _controller: FiveAdminBundle:Crud:edit, options: 'five_admin.crud.program_edit' }

five_admin_program_delete:
    path:     /program{id}/delete
    defaults: { _controller: FiveAdminBundle:Crud:delete, options: 'five_admin.crud.program_delete', entityName: 'AurayCapitalSiteBundle:Program' }

five_admin_program_create:
    path:     /program/create
    defaults: { _controller: FiveAdminBundle:Crud:create, options: 'five_admin.crud.program_create' }

five_admin_gallery_image_listbox:
    path:     /gallery_image/listbox
    defaults: { _controller: FiveAdminBundle:Default:galleryListbox, options: 'five_admin.crud.gallery_image_list' }

five_admin_gallery_image_list:
    path:     /gallery_image
    defaults: { _controller: FiveAdminBundle:Crud:list, options: 'five_admin.crud.gallery_image_list' }

five_admin_gallery_image_create:
    path:     /gallery_image/create
    defaults: { _controller: FiveAdminBundle:Crud:create, options: 'five_admin.crud.gallery_image_create' }

five_admin_gallery_image_edit:
    path:     /gallery_image/{id}/edit
    defaults: { _controller: FiveAdminBundle:Crud:edit, options: 'five_admin.crud.gallery_image_edit' }

five_admin_gallery_image_delete:
    path:     /gallery_image/{id}/delete
    defaults: { _controller: FiveAdminBundle:Crud:delete, options: 'five_admin.crud.gallery_image_delete', entityName: 'FiveCuisinesVerdunBundle:GalleryImage' }


five_admin_gallery_list:
    path:     /gallery/{context}/list
    defaults: { _controller: FiveAdminBundle:Gallery:list, options: 'five_admin.crud.gallery_list' }

five_admin_gallery_edit:
    path:     /gallery/{context}/{id}/edit
    defaults: { _controller: FiveAdminBundle:Gallery:edit, options: 'five_admin.crud.gallery_edit', context: 'realisation', id:'' }

five_admin_gallery_create:
    path:     /gallery/{context}/create
    defaults: { _controller: FiveAdminBundle:Gallery:edit, options: 'five_admin.crud.gallery_edit', id : '', context: 'realisation' }

five_admin_gallery_list_ordering:
    path:     /api/gallery/order
    defaults: { _controller: FiveAdminBundle:Gallery:updateOrder }
    requirements: { _method: POST }






five_admin_gallery_kitchen_list:
    path:     /gallery/kitchen/list
    defaults: { _controller: FiveAdminBundle:Gallery:list, options: 'five_admin.crud.gallery_kitchen_list', context: 'kitchen' }

five_admin_gallery_bathroom_list:
    path:     /gallery/bathroom/list
    defaults: { _controller: FiveAdminBundle:Gallery:list, options: 'five_admin.crud.gallery_bathroom_list', context: 'bathroom' }

five_admin_gallery_kitchen_create:
    path:     /gallery/kitchen/create
    defaults: { _controller: FiveAdminBundle:Gallery:edit, options: 'five_admin.crud.gallery_kitchen_edit', id : '', context: 'kitchen' }

five_admin_gallery_bathroom_create:
    path:     /gallery/bathroom/create
    defaults: { _controller: FiveAdminBundle:Gallery:edit, options: 'five_admin.crud.gallery_bathroom_edit', id : '', context: 'bathroom' }


five_admin_gallery_delete:
    path:     /gallery/{id}/delete
    defaults: { _controller: FiveAdminBundle:Gallery:delete, options: 'five_admin.crud.gallery_delete', entityName: 'FiveAdminBundle:Gallery' }

five_admin_gallery_save:
    path:     /gallery/save
    #path:     /gallery/{id}/edit
    defaults: { _controller: FiveAdminBundle:Gallery:update, options: 'five_admin.crud.gallery_edit' }

five_admin_gallery_publish:
    path:     /gallery/{id}/publish/{enabled}
    #path:     /gallery/{id}/edit
    defaults: { _controller: FiveAdminBundle:Gallery:publish, options: 'five_admin.crud.gallery_publish' }
    requirements:
        enabled: true|false





five_admin_carrousel_gallery_image_list:
    path:     /carrousel_gallery_image
    defaults: { _controller: FiveAdminBundle:Crud:list, options: 'five_admin.crud.gallery_image_list' }

five_admin_carrousel_gallery_image_create:
    path:     /carrousel_gallery_image/create
    defaults: { _controller: FiveAdminBundle:Crud:create, options: 'five_admin.crud.gallery_image_create' }

five_admin_carrousel_gallery_image_edit:
    path:     /carrousel_gallery_image/{id}/edit
    defaults: { _controller: FiveAdminBundle:Crud:edit, options: 'five_admin.crud.gallery_image_edit' }

five_admin_carrousel_gallery_image_delete:
    path:     /carrousel_gallery_image/{id}/delete
    defaults: { _controller: FiveAdminBundle:Crud:delete, options: 'five_admin.crud.gallery_image_delete', entityName: 'FiveCuisinesVerdunBundle:GalleryImage' }





five_admin_gallery_category_list:
    path:     /gallery_category
    defaults: { _controller: FiveAdminBundle:Crud:list, options: 'five_admin.crud.gallery_category_list' }

five_admin_gallery_category_create:
    path:     /gallery_category/create
    defaults: { _controller: FiveAdminBundle:Crud:create, options: 'five_admin.crud.gallery_category_create' }

five_admin_gallery_category_edit:
    path:     /gallery_category/{id}/edit
    defaults: { _controller: FiveAdminBundle:Crud:edit, options: 'five_admin.crud.gallery_category_edit' }

five_admin_gallery_category_delete:
    path:     /gallery_category/{id}/delete
    defaults: { _controller: FiveAdminBundle:Crud:delete, options: 'five_admin.crud.gallery_category_delete', entityName: 'FiveCuisinesVerdunBundle:GalleryCategory' }

five_admin_news_list:
    path:     /news
    defaults: { _controller: FiveAdminBundle:Crud:list, options: 'five_admin.crud.news_list' }

five_admin_news_create:
    path:     /news/create
    defaults: { _controller: FiveAdminBundle:Crud:create, options: 'five_admin.crud.news_create' }

five_admin_news_edit:
    path:     /news/{id}/edit
    defaults: { _controller: FiveAdminBundle:Crud:edit, options: 'five_admin.crud.news_edit' }

five_admin_news_delete:
    path:     /news/{id}/delete
    defaults: { _controller: FiveAdminBundle:Crud:edit, options: 'five_admin.crud.news_edit', entityName: 'AurayCapitalSiteBundle:News' }


five_admin_fivemailer_list:
    path:     /mailer
    defaults: { _controller: FiveAdminBundle:Crud:list, options: 'five_admin.crud.fivemailer_list' }

five_admin_fivemailer_show:
    path:     /mailer/{id}/show
    defaults: { _controller: FiveAdminBundle:Crud:show, options: 'five_admin.crud.fivemailer_show' }

five_admin_angular_gallery_image_edit:
    path:     /angular_gallery_image/{id}/edit
    defaults: { _controller: FiveAdminBundle:Crud:angularEdit, options: 'five_admin.crud.country_edit' }

# lexik_translation_list:
#     pattern:      /translations
#     defaults:     { _controller: "LexikTranslationBundle:Rest:list" }
#     requirements: { _method: GET }

# lexik_translation_update:
#     pattern:      /translations/{id}
#     defaults:     { _controller: "LexikTranslationBundle:Rest:update" }
#     requirements: { _method: PUT }

# lexik_translation_grid:
#     pattern:      /grid
#     defaults:     { _controller: "FiveAdminBundle:Translation:grid" }
#     requirements: { _method: GET }

# lexik_translation_new:
#     pattern:  /new
#     defaults: { _controller: "FiveAdminBundle:Translation:new" }

# lexik_translation_invalidate_cache:
#     pattern:  /invalidate-cache
#     defaults: { _controller: "FiveAdminBundle:Translation:invalidateCache" }


five_admin_blog_list:
    path:     /blog
    #defaults: { _controller: FiveAdminBundle:Crud:list, options: 'five_admin.crud.blog_list' }
    defaults: { _controller: FiveAdminBundle:Blog:list, options: 'five_admin.blog.blog_list' }

five_admin_blog_edit:
    path:     /blog/{id}/edit
    defaults: { _controller: FiveAdminBundle:Blog:edit, options: 'five_admin.blog.blog_edit' }

five_admin_blog_delete:
    path:     /blog/{id}/delete
    defaults: { _controller: FiveAdminBundle:Blog:delete, options: 'five_admin.blog.blog_delete', entityName: 'BloggerBlogBundle:Blog' }

five_admin_blog_create:
    path:     /blog/create
    defaults: { _controller: FiveAdminBundle:Blog:create, options: 'five_admin.blog.blog_create' }
    
five_admin_upload_pictures_blog:
    path:     /upload/blog
    defaults: { _controller: FiveAdminBundle:Blog:uploadPictures }    
    
five_admin_blog_save:
    path:     /blog/save
    defaults: { _controller: FiveAdminBundle:Blog:update, options: 'five_admin.blog.blog_edit' }

