<?php

namespace Five\CuisinesVerdunBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Five\CoreBundle\Repository\AbstractRepository as BaseRepo;
use Doctrine\ORM\QueryBuilder;

/**
 * GalleryRealisationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */


class GalleryRealisationRepository extends BaseRepo
{
}