<?php

namespace Five\CuisinesVerdunBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Five\CuisinesVerdunBundle\Entity\Image;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function add( $category, $url, $type, $fr, $en ) {
        $image = new Image();
        $image->setCategory($category);
        $image->setType($type);
        $image->setUrl($url);
        $image->setFr($fr);
        $image->setEn($en);
        $image->setSortOrder(time());
        $em = $this->getEntityManager();

        $em->persist($image);
        $em->flush();
        return $image->getId();
    }

    public function delete( $id ) {
        $image = $this->findById($id);
        if ($image) {
            $image = $image[0];
            $em = $this->getEntityManager();
            $em->remove($image);
            $em->flush();
         }
    }

    public function update( $id, $fr, $en ) {
        $image = $this->findById($id);
        if ($image) {
            $image = $image[0];
            $em = $this->getEntityManager();
            $image->setFr($fr);
            $image->setEn($en);
            $em->persist($image);
            $em->flush();
         }
    }

    public function sort( $ids ) {
        $em = $this->getEntityManager();
        foreach ($ids as $pos => $id) {
            $image = $this->findById(substr($id,3));
            if ($image) {
                $image = $image[0];
                $image->setSortOrder($pos);
                $em->persist($image);
            }
        }
        $em->flush();
    }

}
