<?php

namespace Five\CuisinesVerdunBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Five\CuisinesVerdunBundle\Entity\Material;

/**
 * MaterialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaterialRepository extends EntityRepository
{

    public function add( $fr, $en, $type, $frDesc, $enDesc ) {
        $material = new Material();
        $material->setFr($fr);
        $material->setEn($en);
        $material->setType($type);
        $material->setFrDescription($frDesc);
        $material->setEnDescription($enDesc);
        $em = $this->getEntityManager();

        $em->persist($material);
        $em->flush();
        return $material->getId();
    }

    public function delete( $id ) {
        $material = $this->findById($id);
        if ($material) {
            $material = $material[0];
            $em = $this->getEntityManager();
            $em->remove($material);
            $em->flush();
         }
    }

    public function edit( $id, $fr, $en ) {
        $material = $this->findById($id);
        if ($material) {
            $material = $material[0];
            $material->setFrDescription($fr);
            $material->setEnDescription($en);
            $em = $this->getEntityManager();
            $em->persist($material);
            $em->flush();
         }
    }

    public function getList($type) {
        $q = "SELECT b FROM FiveCuisinesVerdunBundle:Material b WHERE b.type = '$type'";
        return $this->getEntityManager()->createQuery($q)->getResult();
    }

    public function getImages($room = "") {
        $rv = array();
        $q = "SELECT b.id FROM FiveCuisinesVerdunBundle:Material b";
        if ($room != "") $q .= " WHERE b.type = '$room' ";
        $materials = $this->getEntityManager()->createQuery($q)->getResult();
        foreach ($materials as $material) {
            $tmp = array();
            $q = "SELECT b FROM FiveCuisinesVerdunBundle:Image b WHERE b.type = 'material' and b.category = ".$material['id']." ORDER BY b.sortOrder ASC";
            $results = $this->getEntityManager()->createQuery($q)->getResult();
            foreach ($results as $result) {
                array_push($tmp, array("id" => $result->getId(), "url" => $result->getUrl(), "type" => $result->getType(), "category" => $result->getCategory(), "fr" => $result->getFr(), "en" => $result->getEn(), "sortOrder" => $result->getSortOrder()));
            }
            if (sizeof($tmp) > 0) $rv[$material['id']] = $tmp;
        }
        return $rv;
    }
}
