parameters:

    five_admin.crud.gallery_list:
        page:
            filters: five_admin_gallery_kitchen_list
            name: gallery
            title: "All Realisations Galleries"
            icon: fa icon-camera-2
        entities: 'Five\CuisinesVerdunBundle\Entity\Gallery'
        entity: 'Five\CuisinesVerdunBundle\Entity\Gallery'
        template: 'FiveAdminBundle:Action:list.html.twig'
        edit_action:
            path: 'five_admin_gallery_edit'
            parameters: { 'id': null, context:'realisation' }
        create_action:
            path: 'five_admin_gallery_create'
            parameters: {context:'realisation'}
        delete_action:
            path: 'five_admin_gallery_delete'
            parameters: { 'id': null }
        publish_action:
            path: 'five_admin_publish'
            parameters: { 'id': null }
        expose:
            # Ne pas changer la premiere colonne de cette table car elle sert à l'api de sorting afin d'ordonnée les gallerie
            - { label: 'ID', call: 'id' }
            - { label: 'Position', call: 'position' }
            - { label: 'Cover', call: 'getCover', type:'image' }
            - { label: Images, call: getImagesCount}
            # - { label: 'Parent', call: 'parent' }
            # - { label: 'Category', call: 'name' }
            - { label: 'Title FR', call: 'titleFr' }
            - { label: 'Title EN', call: 'titleEn' }
            #- { label: 'Src', call: 'src' }
            - { label: 'Categories', call: 'getAllCategoriesLabelList', type: 'label' }
            #- { label: 'Created At', call: 'createdAt', type: 'date', format: 'Y-m-d' }
            - { label: 'Published', action: 'publish_action' }
            - { label: 'Edit', action: 'edit_action' }
            - { label: 'Delete', action: 'delete_action' }


    five_admin.crud.gallery_bathroom_list:
        page:
            filters: true
            filters_options: {context:bathroom}
            name: gallery
            icon: fa icon-camera-2
            title: "All Realisations Galleries"
        entities: 'Five\CuisinesVerdunBundle\Entity\Gallery'
        template: 'FiveAdminBundle:Action:list.html.twig'
        edit_action:
            path: 'five_admin_gallery_edit'
            parameters: { 'id': null, context:'bathroom' }
        create_action:
            path: 'five_admin_gallery_create'
            parameters: {context:'bathroom'}
        delete_action:
            path: 'five_admin_gallery_delete'
            parameters: { 'id': null }
        expose:
            - { label: 'ID', call: 'id' }
            - { label: 'Image', call: 'getCover', type:'image' }
            - { label: Total, call: getImagesCount}
            # - { label: 'Parent', call: 'parent' }
            # - { label: 'Category', call: 'name' }
            - { label: 'Title FR', call: 'titleFr' }
            - { label: 'Title EN', call: 'titleEn' }
            #- { label: 'Src', call: 'src' }
            - { label: 'Categories', call: 'getAllCategoriesNameList', type:'label' }
            #- { label: 'Created At', call: 'createdAt', type: 'date', format: 'Y-m-d' }
            - { label: 'Edit', action: 'edit_action' }
            - { label: 'Delete', action: 'delete_action' }

    five_admin.crud.gallery_kitchen_list:
        page:
            icon: fa icon-camera-2
            filters: true
            filters_options: {context:kitchen}
            name: gallery
            title: "All Realisations Galleries"
        entities: 'FiveCuisinesVerdunBundle:Gallery'
        template: 'FiveAdminBundle:Action:list.html.twig'
        edit_action:
            path: 'five_admin_gallery_edit'
            parameters: { 'id': null, context:'kitchen' }
        create_action:
            path: 'five_admin_gallery_create'
            parameters: {context:'kitchen'}
        delete_action:
            path: 'five_admin_gallery_delete'
            parameters: { 'id': null }
        expose:
            - { label: 'ID', call: 'id' }
            - { label: 'Image', call: 'getCover', type:'image' }
            - { label: Name, call: getImagesCount}
            - { label: Total Images, call: getImagesCount}
            # - { label: 'Parent', call: 'parent' }
            # - { label: 'Category', call: 'name' }
            - { label: 'Title FR', call: 'titleFr' }
            - { label: 'Title EN', call: 'titleEn' }
            #- { label: 'Src', call: 'src' }
            - { label: 'Categories', call: 'getAllCategoriesNameList', type: 'label' }
            #- { label: 'Created At', call: 'createdAt', type: 'date', format: 'Y-m-d' }
            - { label: 'Edit', action: 'edit_action' }
            - { label: 'Delete', action: 'delete_action' }

    five_admin.crud.gallery_edit:
        page:
            icon: fa icon-camera-2
            title: "Edit Gallery Images ID#"
        entity: 'FiveCuisinesVerdunBundle:Gallery'
        template: 'FiveAdminBundle:Action:edit_gallery.html.twig'
        form: 'five.form.gallery'
        form_action: 
            path: 'five_admin_gallery_edit'
            parameters: { 'id': null, context:'realisation' }
        success_action: 
            path: 'five_admin_gallery_list'
            parameters: {context:'realisation'}

    five_admin.crud.gallery_create:
        page:
            icon: fa icon-camera-2
            title: "Create a new Gallery Image"
        entity: 'FiveCuisinesVerdunBundle:Gallery'
        template: 'FiveAdminBundle:Action:edit_gallery.html.twig'
        form: 'five.form.gallery'        
        form_action: 
            path: 'five_admin_gallery_create'
            parameters: {context:'realisation'}
        success_action: 
            path: 'five_admin_gallery_list'
            parameters: {context:'realisation'}

    five_admin.crud.gallery_kitchen_create:
        page:
            icon: fa icon-camera-2
            title: "Create a new Gallery Image"
        entity: 'FiveCuisinesVerdunBundle:Gallery'
        template: 'FiveAdminBundle:Action:edit_gallery.html.twig'
        form: 'five.form.gallery'        
        form_action: 
            path: 'five_admin_gallery_create'
            parameters: {context:'kitchen'}
        success_action: 
            path: 'five_admin_gallery_kitchen_list'
            parameters: {context:'kitchen'}

    five_admin.crud.gallery_bathroom_create:
        page:
            icon: fa icon-camera-2
            title: "Create a new Gallery Image"
        entity: 'FiveCuisinesVerdunBundle:Gallery'
        template: 'FiveAdminBundle:Action:edit_gallery.html.twig'
        form: 'five.form.gallery'        
        form_action: 
            path: 'five_admin_gallery_create'
            parameters: {context:'bathroom'}
        success_action: 
            path: 'five_admin_gallery_bathroom_list'
            parameters: {context:'bathroom'}



    five_admin.crud.gallery_delete:
        page:
            icon: fa icon-camera-2
            title: "Edit User ID#"
        entity: 'FiveCuisinesVerdunBundle:Gallery'
        template: 'FiveAdminBundle:Action:delete-modal.html.twig'
        form: 'five.form.delete'
        form_action: 
            path: 'five_admin_gallery_delete'
            parameters: { 'id': null }
        success_action: 
            path: 'five_admin_gallery_list'
            parameters: {}








    five_admin.crud.gallery_category_list:
        page:
            filters: false
            icon: fa icon-camera-2
            name: gallery_category
            title: "All Gallery Categories"
        entities: 'Five\CuisinesVerdunBundle\Entity\GalleryCategory'
        template: 'FiveAdminBundle:Action:list.html.twig'
        edit_action:
            path: 'five_admin_gallery_category_edit'
            parameters: { 'id': null }
        create_action:
            path: 'five_admin_gallery_category_create'
            parameters: {}
        delete_action:
            path: 'five_admin_gallery_category_delete'
            parameters: { 'id': null }
        expose:
            - { label: 'ID', call: 'id' }
            - { label: 'Parent', call: 'parent' }
            - { label: 'Category', call: 'name' }
            - { label: 'Title FR', call: 'titleFr' }
            - { label: 'Title EN', call: 'titleEn' }
            #- { label: 'Src', call: 'src' }
            #- { label: 'Categories', call: 'getAllCategoriesNameList' }
            #- { label: 'Created At', call: 'createdAt', type: 'date', format: 'Y-m-d' }
            - { label: 'Edit', action: 'edit_action' }
            - { label: 'Delete', action: 'delete_action' }


    five_admin.crud.gallery_image_list:
        page:
            filters: true
            name: gallery_image
            title: "All Gallery Images"
        entities: 'Five\CuisinesVerdunBundle\Entity\GalleryImage'
        template: 'FiveAdminBundle:Action:list.html.twig'
        edit_action:
            path: 'five_admin_gallery_image_edit'
            parameters: { 'id': null }
        create_action:
            path: 'five_admin_gallery_image_create'
            parameters: {}
        delete_action:
            path: 'five_admin_gallery_image_delete'
            parameters: { 'id': null }
        expose:
            - { label: 'ID', call: 'id' }
            - { label: 'Image', call: 'src', type:'image' }
            - { label: 'Position', call: 'position' }
            - { label: 'Title FR', call: 'titleFr' }
            - { label: 'Title EN', call: 'titleEn' }
            - { label: 'Src', call: 'src' }
            - { label: 'Categories', call: 'getAllCategoriesNameList' }
            #- { label: 'Created At', call: 'createdAt', type: 'date', format: 'Y-m-d' }
            - { label: 'Edit', action: 'edit_action' }
            - { label: 'Delete', action: 'delete_action' }

    five_admin.crud.gallery_image_edit:
        page:
            icon: fa icon-camera-2
            title: "Edit Gallery Images ID#"
        entity: 'Five\CuisinesVerdunBundle\Entity\GalleryImage'
        template: 'FiveAdminBundle:Action:edit_gallery_image.html.twig'
        form: 'five.form.gallery_image'
        form_action: 
            path: 'five_admin_gallery_image_edit'
            parameters: { 'id': null }
        success_action: 
            path: 'five_admin_gallery_image_list'
            parameters: {}

    five_admin.crud.gallery_image_create:
        page:
            title: "Create a new Gallery Image"
        entity: 'Five\CuisinesVerdunBundle\Entity\GalleryImage'
        template: 'FiveAdminBundle:Action:edit_gallery_image.html.twig'
        form: 'five.form.gallery_image'        
        form_action: 
            path: 'five_admin_gallery_image_create'
            parameters: {}
        success_action: 
            path: 'five_admin_gallery_image_list'
            parameters: {}




    five_admin.crud.carrousel_gallery_image_list:
        page:
            icon: fa icon-camera-2
            filters: true
            name: gallery_image
            title: "Carrousels - Toutes les images"
        entities: 'Five\CuisinesVerdunBundle\Entity\GalleryImage'
        template: 'FiveAdminBundle:Action:list.html.twig'
        edit_action:
            path: 'five_admin_carrousel_gallery_image_edit'
            parameters: { 'id': null }
        create_action:
            path: 'five_admin_carrousel_gallery_image_create'
            parameters: {}
        delete_action:
            path: 'five_admin_carrousel_gallery_image_delete'
            parameters: { 'id': null }
        expose:
            - { label: 'ID', call: 'id' }
            - { label: 'Image', call: 'src', type:'image' }
            - { label: 'Position', call: 'position' }
            - { label: 'Title FR', call: 'titleFr' }
            - { label: 'Title EN', call: 'titleEn' }
            - { label: 'Src', call: 'src' }
            - { label: 'Categories', call: 'getAllCategoriesNameList' }
            #- { label: 'Created At', call: 'createdAt', type: 'date', format: 'Y-m-d' }
            - { label: 'Edit', action: 'edit_action' }
            - { label: 'Delete', action: 'delete_action' }

    five_admin.crud.carrousel_gallery_image_edit:
        page:
            title: "Modifier Carrousel Image ID#"
        entity: 'Five\CuisinesVerdunBundle\Entity\GalleryImage'
        template: 'FiveAdminBundle:Action:edit_gallery_image.html.twig'
        form: 'five.form.gallery_image'
        form_action: 
            path: 'five_admin_carrousel_gallery_image_edit'
            parameters: { 'id': null }
        success_action: 
            path: 'five_admin_carrousel_gallery_image_list'
            parameters: {}

    five_admin.crud.carrousel_gallery_image_create:
        page:
            title: "Create a new Gallery Image"
            icon: fa icon-camera-2
        entity: 'Five\CuisinesVerdunBundle\Entity\GalleryImage'
        template: 'FiveAdminBundle:Action:edit_gallery_image.html.twig'
        form: 'five.form.gallery_image'        
        form_action: 
            path: 'five_admin_carrousel_gallery_image_create'
            parameters: {}
        success_action: 
            path: 'five_admin_carrousel_gallery_image_list'
            parameters: {}

    five_admin.crud.program_delete:
        page:
            title: "Edit User ID#"
            icon: fa icon-camera-2
        entity: 'Five\CuisinesVerdunBundle\Entity\GalleryImage'
        template: 'FiveAdminBundle:Action:delete-modal.html.twig'
        form: 'five.form.delete'
        form_action: 
            path: 'five_admin_gallery_image_delete'
            parameters: { 'id': null }
        success_action: 
            path: 'five_admin_gallery_image_list'
            parameters: {}