parameters:
    five_admin.crud.fivemailer_list:
        page:
            title: "All Emails Sent"
        entities: 'Five\MailerBundle\Entity\Mailer'
        template: 'FiveAdminBundle:Action:list.html.twig'
        edit_action:
            path: 'five_admin_fivemailer_show'
            parameters: { 'id': null }
        expose:
            - { label: 'ID', call: 'id' }
            - { label: 'Context', call: 'context' }
            - { label: 'Type', call: 'type' }
            # - { label: 'Url', call: 'url' }
            - { label: 'From', call: 'fromEmail' }
            - { label: 'toEmail', call: 'toEmail' }
            # - { label: 'Message', call: 'body' }
            - { label: 'Env', call: 'env' }
            - { label: 'Domain', call: 'domain' }
            - { label: 'Created At', call: 'createdAt', type: 'date', format: 'Y-m-d' }
            - { label: 'Show', action: 'edit_action' }