parameters:

    five_admin.crud.user_list:
        page:
            title: "All Users"    
        entities: 'Five\AdminBundle\Entity\User'
        template: 'FiveAdminBundle:Action:list.html.twig'
        edit_action:
            path: 'five_admin_user_edit'
            parameters: { 'id': null }
        delete_action:
            path: 'five_admin_user_delete'
            parameters: { 'id': null }
        expose:
            - { label: 'ID', call: 'id' }
            - { label: 'First Name', call: 'firstName' }
            - { label: 'Last Name', call: 'lastName' }
            - { label: 'Email', call: 'email' }
            - { label: 'Gender', call: 'gender' }
            #- { label: 'Address', call: 'address' }
            - { label: 'Opt-in', call: 'optinNewsletter', type: 'bool', format: { true: 'Yes', false: 'No' } }
            #- { label: 'Created At', call: 'createdAt', type: 'date', format: 'Y-m-d' }
            - { label: 'Edit', action: 'edit_action' }
            - { label: 'Delete', action: 'delete_action' }

    five_admin.crud.user_delete:
        page:
            title: "Edit User ID#"
        entity: 'Five\AdminBundle\Entity\User'
        template: 'FiveAdminBundle:Action:delete-modal.html.twig'
        form: 'five.form.delete'
        form_action: 
            path: 'five_admin_user_delete'
            parameters: { 'id': null }
        success_action: 
            path: 'five_admin_user_list'
            parameters: {}

    five_admin.crud.user_edit:
        page:
            title: "Edit User ID#"
        entity: 'Five\AdminBundle\Entity\User'
        template: 'FiveAdminBundle:Action:edit.html.twig'
        form: 'five.form.user'
        form_action: 
            path: 'five_admin_user_edit'
            parameters: { 'id': null }
        success_action: 
            path: 'five_admin_user_list'
            parameters: {}

    five_admin.crud.user_create:
        page:
            title: "Create a new User"
        entity: 'Five\AdminBundle\Entity\User'
        template: 'FiveAdminBundle:Action:edit.html.twig'
        form: 'five.form.user'
        form_action: 
            path: 'five_admin_user_create'
            parameters: {}
        success_action: 
            path: 'five_admin_user_list'
            parameters: {}