parameters:
    five.mailer_entity.class:         Five\MailerBundle\Entity\Mailer
    five.mailer_manager.class:        Five\MailerBundle\Manager\MailerManager
    five.mailer_factory.class:        Five\MailerBundle\Factory\MailerFactory
    five.mailer_entity_manager.class: Five\MailerBundle\Manager\MailerEntityManager
    five.sendemail_interceptor.class: Five\MailerBundle\Aop\SendEmailInterceptor
    five.sendemail_pointcut.class:    Five\MailerBundle\Aop\SendEmailPointcut

services:

    five.mailer_entity_manager:
        class:     "%five.mailer_entity_manager.class%"
        arguments: [ @doctrine, @request_stack, '%five.mailer_entity.class%' ]

    five.mailer_factory:
        class:     "%five.mailer_factory.class%"
        arguments: [ @mailer, @templating ]

    five.mailer_manager:
        class: "%five.mailer_manager.class%"
        calls:
            - [ setMailer,       [ "@mailer" ] ]
            - [ setTemplating,   [ "@templating" ] ]
            - [ setLogger,       [ "@logger" ] ]
            - [ setRequestStack, [ "@request_stack" ] ]
            - [ setEnvironment,  [ '%kernel.environment%' ] ]

        # factory_service:  five.mailer_factory
        # factory_method:   get

    # five.mailer_listener:
    #     class: Five\MailerBundle\EventListener\MailerManagerListener
    #     tags:
    #         - { name: kernel.event_listener, event: five.mailer_send, method: handler }
            # - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
            #         tags:

    five.sendemail_interceptor:
        class:     "%five.sendemail_interceptor.class%"
        arguments: [ @annotation_reader, @five.mailer_entity_manager ]

    five.sendemail_pointcut:
        class:     "%five.sendemail_pointcut.class%"
        arguments: [ @annotation_reader ]
        tags:
            - { name: jms_aop.pointcut, interceptor: five.sendemail_interceptor }